// ============================================
// WINE ENCYCLOPEDIA - GRAPE VARIETIES
// ============================================

import { GrapeVariety } from '@/types/wineEncyclopedia';

export const RED_GRAPE_VARIETIES: GrapeVariety[] = [
  {
    id: 'cabernet-sauvignon',
    slug: 'cabernet-sauvignon',
    name: 'Cabernet Sauvignon',
    color: 'czerwony',
    origin: 'Bordeaux, Francja',
    primaryRegions: ['Bordeaux', 'Napa Valley', 'Coonawarra', 'Maipo Valley', 'Toskania'],
    description: 'Król szczepów czerwonych. Cabernet Sauvignon to najpopularniejsza i najbardziej rozpoznawalna odmiana winorośli na świecie. Daje wina o głębokiej barwie, wyraźnych taninach i potencjale do długiego dojrzewania.',
    characteristics: {
      body: 5,
      tannins: 5,
      acidity: 4,
      sweetness: 1,
    },
    flavorProfile: {
      primary: ['Czarna porzeczka', 'Śliwka', 'Wiśnia', 'Jeżyna'],
      secondary: ['Zielona papryka', 'Mięta', 'Eukaliptus'],
      tertiary: ['Cedr', 'Tytoń', 'Wanilia', 'Grafit', 'Skóra'],
    },
    agingPotential: '5-25+ lat dla top cru',
    foodPairings: ['Stek z grilla', 'Jagnięcina', 'Dojrzałe sery', 'Gulasz wołowy'],
    servingTemp: { min: 16, max: 18 },
    image: {
      url: 'https://images.unsplash.com/photo-1596142046671-34bcc9f496e6?w=800',
      alt: 'Winogrona Cabernet Sauvignon',
    },
    famousWines: ['Château Margaux', 'Opus One', 'Sassicaia', 'Screaming Eagle'],
  },
  {
    id: 'merlot',
    slug: 'merlot',
    name: 'Merlot',
    color: 'czerwony',
    origin: 'Bordeaux, Francja',
    primaryRegions: ['Bordeaux (Pomerol, Saint-Émilion)', 'Toskania', 'Chile', 'California'],
    description: 'Najbardziej sadzony szczep w Bordeaux. Merlot daje wina bardziej miękkie i przystępne niż Cabernet Sauvignon, z aksamitnymi taninami i owocowym charakterem.',
    characteristics: {
      body: 4,
      tannins: 3,
      acidity: 3,
      sweetness: 1,
    },
    flavorProfile: {
      primary: ['Śliwka', 'Wiśnia', 'Malina', 'Figa'],
      secondary: ['Czekolada', 'Kawa'],
      tertiary: ['Wanilia', 'Liść laurowy', 'Cedr'],
    },
    agingPotential: '3-15 lat',
    foodPairings: ['Kaczka', 'Pasta z sosem mięsnym', 'Ser Brie', 'Pieczony kurczak'],
    servingTemp: { min: 15, max: 17 },
    image: {
      url: 'https://images.unsplash.com/photo-1568584711271-7b8673c93a42?w=800',
      alt: 'Winogrona Merlot',
    },
    famousWines: ['Château Pétrus', 'Le Pin', 'Masseto', 'Duckhorn Merlot'],
  },
  {
    id: 'pinot-noir',
    slug: 'pinot-noir',
    name: 'Pinot Noir',
    alternateNames: ['Pinot Nero', 'Spätburgunder', 'Blauburgunder'],
    color: 'czerwony',
    origin: 'Burgundia, Francja',
    primaryRegions: ['Burgundia', 'Szampania', 'Oregon', 'Central Otago', 'Alsacja'],
    description: 'Uważany za najbardziej elegancki szczep czerwony. Trudny w uprawie, kapryśny i wymagający, ale dający wina o niezrównanej finezji i złożoności.',
    characteristics: {
      body: 3,
      tannins: 2,
      acidity: 4,
      sweetness: 1,
    },
    flavorProfile: {
      primary: ['Wiśnia', 'Malina', 'Truskawka', 'Żurawina'],
      secondary: ['Fiolek', 'Róża'],
      tertiary: ['Grzyby', 'Liść jesieni', 'Trufa', 'Podszyt leśny'],
    },
    agingPotential: '3-20+ lat dla Grand Cru',
    foodPairings: ['Łosoś', 'Kaczka', 'Kurczak pieczony', 'Grzyby', 'Tuńczyk'],
    servingTemp: { min: 14, max: 16 },
    image: {
      url: 'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=800',
      alt: 'Winogrona Pinot Noir',
    },
    famousWines: ['Romanée-Conti', 'La Tâche', 'Chambertin', 'Domaine Leroy'],
  },
  {
    id: 'syrah',
    slug: 'syrah',
    name: 'Syrah / Shiraz',
    alternateNames: ['Shiraz', 'Hermitage'],
    color: 'czerwony',
    origin: 'Dolina Rodanu, Francja',
    primaryRegions: ['Dolina Rodanu', 'Barossa Valley', 'McLaren Vale', 'Waszyngton'],
    description: 'Potężny, pełny i aromatyczny. Pod nazwą Syrah występuje w Europie, jako Shiraz w Australii. Daje wina intensywne, korzenne, z nutami ciemnych owoców.',
    characteristics: {
      body: 5,
      tannins: 4,
      acidity: 3,
      sweetness: 1,
    },
    flavorProfile: {
      primary: ['Jeżyna', 'Borówka', 'Oliwki'],
      secondary: ['Pieprz czarny', 'Goździki', 'Lawenda'],
      tertiary: ['Bekon', 'Skóra', 'Dym wędzarniczy'],
    },
    agingPotential: '5-20 lat',
    foodPairings: ['Dziczyzna', 'Grillowane mięsa', 'BBQ', 'Ostre sery'],
    servingTemp: { min: 16, max: 18 },
    image: {
      url: 'https://images.unsplash.com/photo-1596142046671-34bcc9f496e6?w=800',
      alt: 'Winogrona Syrah',
    },
    famousWines: ['Hermitage', 'Côte-Rôtie', 'Penfolds Grange', 'Guigal La Mouline'],
  },
  {
    id: 'sangiovese',
    slug: 'sangiovese',
    name: 'Sangiovese',
    alternateNames: ['Brunello', 'Prugnolo Gentile', 'Morellino'],
    color: 'czerwony',
    origin: 'Toskania, Włochy',
    primaryRegions: ['Toskania (Chianti, Montalcino, Montepulciano)', 'Emilia-Romania', 'Umbria'],
    description: 'Serce Toskanii. Sangiovese to król włoskich szczepów, tworzący Chianti, Brunello di Montalcino i Vino Nobile. Wina charakteryzują się wysoką kwasowością i nutami wiśni.',
    characteristics: {
      body: 4,
      tannins: 4,
      acidity: 5,
      sweetness: 1,
    },
    flavorProfile: {
      primary: ['Wiśnia', 'Śliwka', 'Pomidor suszony'],
      secondary: ['Oregano', 'Tymianek', 'Fiolek'],
      tertiary: ['Skóra', 'Tytoń', 'Liść herbaty', 'Balsamico'],
    },
    agingPotential: '5-25 lat (Brunello)',
    foodPairings: ['Pasta z pomidorami', 'Pizza', 'Bistecca alla fiorentina', 'Pecorino'],
    servingTemp: { min: 16, max: 18 },
    image: {
      url: 'https://images.unsplash.com/photo-1596142046671-34bcc9f496e6?w=800',
      alt: 'Winogrona Sangiovese',
    },
    famousWines: ['Brunello di Montalcino', 'Tignanello', 'Chianti Classico Riserva'],
  },
  {
    id: 'nebbiolo',
    slug: 'nebbiolo',
    name: 'Nebbiolo',
    alternateNames: ['Spanna', 'Chiavennasca'],
    color: 'czerwony',
    origin: 'Piemont, Włochy',
    primaryRegions: ['Piemont (Barolo, Barbaresco)', 'Lombardia (Valtellina)'],
    description: 'Najszlachetniejszy włoski szczep. Nebbiolo daje wina o jasnej barwie, ale potężnych taninach i niezwykłej złożoności. Barolo nazywane jest "winem królów".',
    characteristics: {
      body: 4,
      tannins: 5,
      acidity: 5,
      sweetness: 1,
    },
    flavorProfile: {
      primary: ['Wiśnia', 'Malina', 'Róża'],
      secondary: ['Fiolek', 'Anyż'],
      tertiary: ['Smoła', 'Trufa', 'Liść herbaty', 'Skóra', 'Suszone zioła'],
    },
    agingPotential: '10-30+ lat',
    foodPairings: ['Trufa biała', 'Risotto', 'Brasato', 'Dojrzałe sery'],
    servingTemp: { min: 16, max: 18 },
    image: {
      url: 'https://images.unsplash.com/photo-1596142046671-34bcc9f496e6?w=800',
      alt: 'Winogrona Nebbiolo',
    },
    famousWines: ['Barolo', 'Barbaresco', 'Giacomo Conterno', 'Bruno Giacosa'],
  },
  {
    id: 'tempranillo',
    slug: 'tempranillo',
    name: 'Tempranillo',
    alternateNames: ['Tinto Fino', 'Tinta del País', 'Aragonez'],
    color: 'czerwony',
    origin: 'Rioja, Hiszpania',
    primaryRegions: ['Rioja', 'Ribera del Duero', 'Toro', 'Portugalia (Alentejo)'],
    description: 'Główny szczep Hiszpanii. Tempranillo ("wczesny" po hiszpańsku) dojrzewa wcześnie i daje wina eleganckie, z wyraźnym wpływem dębu.',
    characteristics: {
      body: 4,
      tannins: 3,
      acidity: 3,
      sweetness: 1,
    },
    flavorProfile: {
      primary: ['Wiśnia', 'Śliwka', 'Pomidor'],
      secondary: ['Wanilia', 'Kokos (od dębu)'],
      tertiary: ['Skóra', 'Tytoń', 'Dill'],
    },
    agingPotential: '5-20 lat',
    foodPairings: ['Jagnięcina', 'Tapas', 'Chorizo', 'Manchego'],
    servingTemp: { min: 16, max: 18 },
    image: {
      url: 'https://images.unsplash.com/photo-1596142046671-34bcc9f496e6?w=800',
      alt: 'Winogrona Tempranillo',
    },
    famousWines: ['Vega Sicilia', 'Pingus', 'La Rioja Alta Gran Reserva'],
  },
  {
    id: 'malbec',
    slug: 'malbec',
    name: 'Malbec',
    alternateNames: ['Côt', 'Auxerrois'],
    color: 'czerwony',
    origin: 'Cahors, Francja (ale rozsławiony w Argentynie)',
    primaryRegions: ['Mendoza (Argentyna)', 'Cahors (Francja)', 'Chile'],
    description: 'Dawniej marginalny szczep z Francji, dziś gwiazda Argentyny. Malbec z Mendozy daje wina intensywne, gęste, z aksamitnymi taninami.',
    characteristics: {
      body: 5,
      tannins: 4,
      acidity: 3,
      sweetness: 1,
    },
    flavorProfile: {
      primary: ['Śliwka', 'Jeżyna', 'Czarna wiśnia'],
      secondary: ['Kakao', 'Kawa'],
      tertiary: ['Wanilia', 'Skóra', 'Szata kadzidlana'],
    },
    agingPotential: '3-15 lat',
    foodPairings: ['Stek argentyński', 'Empanadas', 'Grillowane mięsa', 'Blue cheese'],
    servingTemp: { min: 16, max: 18 },
    image: {
      url: 'https://images.unsplash.com/photo-1596142046671-34bcc9f496e6?w=800',
      alt: 'Winogrona Malbec',
    },
    famousWines: ['Catena Zapata', 'Achaval-Ferrer', 'Zuccardi'],
  },
];

export const WHITE_GRAPE_VARIETIES: GrapeVariety[] = [
  {
    id: 'chardonnay',
    slug: 'chardonnay',
    name: 'Chardonnay',
    color: 'biały',
    origin: 'Burgundia, Francja',
    primaryRegions: ['Burgundia', 'Szampania', 'California', 'Australia', 'Chile'],
    description: 'Najbardziej wszechstronny i popularny biały szczep. Chardonnay to "płótno malarza" - oddaje terroir i styl winiarski jak żaden inny.',
    characteristics: {
      body: 4,
      acidity: 3,
      sweetness: 1,
    },
    flavorProfile: {
      primary: ['Jabłko', 'Gruszka', 'Cytrusy'],
      secondary: ['Masło', 'Brioche (po fermentacji malolaktycznej)'],
      tertiary: ['Wanilia', 'Karmel', 'Orzech laskowy', 'Dym'],
    },
    agingPotential: '3-10+ lat (Grand Cru)',
    foodPairings: ['Homary', 'Kurczak w sosie śmietanowym', 'Ryby', 'Sery miękkie'],
    servingTemp: { min: 10, max: 12 },
    image: {
      url: 'https://images.unsplash.com/photo-1596142046671-34bcc9f496e6?w=800',
      alt: 'Winogrona Chardonnay',
    },
    famousWines: ['Montrachet', 'Chablis Grand Cru', 'Corton-Charlemagne', 'Kistler'],
  },
  {
    id: 'sauvignon-blanc',
    slug: 'sauvignon-blanc',
    name: 'Sauvignon Blanc',
    alternateNames: ['Fumé Blanc'],
    color: 'biały',
    origin: 'Dolina Loary, Francja',
    primaryRegions: ['Loire (Sancerre, Pouilly-Fumé)', 'Bordeaux', 'Marlborough', 'Chile'],
    description: 'Aromatyczny, świeży i wyrazisty. Sauvignon Blanc to synonim rześkości, z charakterystycznymi nutami ziołowymi i cytrusowymi.',
    characteristics: {
      body: 2,
      acidity: 5,
      sweetness: 1,
    },
    flavorProfile: {
      primary: ['Grejpfrut', 'Limonka', 'Marakuja', 'Agrest'],
      secondary: ['Trawa', 'Pokrzywa', 'Papryka zielona'],
      tertiary: ['Krzemień (minerały)'],
    },
    agingPotential: '1-5 lat',
    foodPairings: ['Kozi ser', 'Owoce morza', 'Sałatki', 'Szparagi'],
    servingTemp: { min: 8, max: 10 },
    image: {
      url: 'https://images.unsplash.com/photo-1596142046671-34bcc9f496e6?w=800',
      alt: 'Winogrona Sauvignon Blanc',
    },
    famousWines: ['Sancerre', 'Pouilly-Fumé', 'Cloudy Bay', 'Domaine Vacheron'],
  },
  {
    id: 'riesling',
    slug: 'riesling',
    name: 'Riesling',
    color: 'biały',
    origin: 'Nadrenia, Niemcy',
    primaryRegions: ['Mosel', 'Rheingau', 'Alzacja', 'Austria', 'Australia (Clare Valley)'],
    description: 'Jeden z najszlachetniejszych białych szczepów. Riesling wyróżnia się niezwykłą elegancją, wysoką kwasowością i zdolnością do wyrażania terroir.',
    characteristics: {
      body: 2,
      acidity: 5,
      sweetness: 3, // Varies widely
    },
    flavorProfile: {
      primary: ['Jabłko zielone', 'Limonka', 'Brzoskwinia', 'Morela'],
      secondary: ['Kwiat pomarańczy', 'Jaśmin'],
      tertiary: ['Nuta naftowa (petrol)', 'Miód', 'Imbir'],
    },
    agingPotential: '5-30+ lat',
    foodPairings: ['Kuchnia azjatycka', 'Pikantne potrawy', 'Pâté', 'Foie gras (wersje słodkie)'],
    servingTemp: { min: 8, max: 10 },
    image: {
      url: 'https://images.unsplash.com/photo-1596142046671-34bcc9f496e6?w=800',
      alt: 'Winogrona Riesling',
    },
    famousWines: ['Egon Müller', 'JJ Prüm', 'Trimbach Clos Sainte Hune', 'Grosset'],
  },
  {
    id: 'pinot-grigio',
    slug: 'pinot-grigio',
    name: 'Pinot Grigio / Pinot Gris',
    alternateNames: ['Pinot Gris', 'Grauburgunder', 'Ruländer'],
    color: 'biały',
    origin: 'Burgundia, Francja',
    primaryRegions: ['Włochy (Alto Adige, Friuli)', 'Alzacja', 'Oregon', 'Niemcy'],
    description: 'Pod nazwą Pinot Grigio we Włoszech daje lekkie, świeże wina. Jako Pinot Gris w Alzacji - pełniejsze i bogatsze.',
    characteristics: {
      body: 3,
      acidity: 3,
      sweetness: 1,
    },
    flavorProfile: {
      primary: ['Gruszka', 'Jabłko', 'Cytrus'],
      secondary: ['Migdały', 'Miód'],
      tertiary: ['Przyprawy korzenne (Alzacja)'],
    },
    agingPotential: '1-5 lat',
    foodPairings: ['Owoce morza', 'Risotto', 'Lekkie pasty', 'Sałatki'],
    servingTemp: { min: 8, max: 10 },
    image: {
      url: 'https://images.unsplash.com/photo-1596142046671-34bcc9f496e6?w=800',
      alt: 'Winogrona Pinot Grigio',
    },
    famousWines: ['Alois Lageder', 'Jermann', 'Zind-Humbrecht'],
  },
  {
    id: 'gewurztraminer',
    slug: 'gewurztraminer',
    name: 'Gewürztraminer',
    color: 'biały',
    origin: 'Tyrol Południowy (Tramin)',
    primaryRegions: ['Alzacja', 'Niemcy', 'Alto Adige', 'Nowa Zelandia'],
    description: 'Najbardziej aromatyczny z białych szczepów. "Gewürz" oznacza "przyprawowy" - wina pachną różą, liczi i egzotycznymi przyprawami.',
    characteristics: {
      body: 4,
      acidity: 2,
      sweetness: 3,
    },
    flavorProfile: {
      primary: ['Liczi', 'Róża', 'Mango', 'Marakuja'],
      secondary: ['Imbir', 'Cynamon', 'Goździki'],
      tertiary: ['Miód', 'Muszkat'],
    },
    agingPotential: '2-10 lat',
    foodPairings: ['Kuchnia azjatycka', 'Foie gras', 'Ostre curry', 'Sery pleśniowe'],
    servingTemp: { min: 10, max: 12 },
    image: {
      url: 'https://images.unsplash.com/photo-1596142046671-34bcc9f496e6?w=800',
      alt: 'Winogrona Gewürztraminer',
    },
    famousWines: ['Zind-Humbrecht', 'Trimbach', 'Hugel'],
  },
  {
    id: 'viognier',
    slug: 'viognier',
    name: 'Viognier',
    color: 'biały',
    origin: 'Dolina Rodanu, Francja',
    primaryRegions: ['Condrieu', 'Languedoc', 'California', 'Australia'],
    description: 'Egzotyczny i pełny szczep z północnego Rodanu. Viognier daje wina aromatyczne, z nutami moreli i kwiatów.',
    characteristics: {
      body: 4,
      acidity: 2,
      sweetness: 1,
    },
    flavorProfile: {
      primary: ['Morela', 'Brzoskwinia', 'Mango'],
      secondary: ['Jaśmin', 'Akacja', 'Gardenia'],
      tertiary: ['Wanilia', 'Krem'],
    },
    agingPotential: '1-5 lat',
    foodPairings: ['Dania z curry', 'Homary', 'Drób w sosach kremowych'],
    servingTemp: { min: 10, max: 12 },
    image: {
      url: 'https://images.unsplash.com/photo-1596142046671-34bcc9f496e6?w=800',
      alt: 'Winogrona Viognier',
    },
    famousWines: ['Condrieu', 'Château-Grillet', 'Yalumba Virgilius'],
  },
];

export const ALL_GRAPE_VARIETIES: GrapeVariety[] = [
  ...RED_GRAPE_VARIETIES,
  ...WHITE_GRAPE_VARIETIES,
];

export const getGrapeBySlug = (slug: string): GrapeVariety | undefined => {
  return ALL_GRAPE_VARIETIES.find((grape) => grape.slug === slug);
};

export const getGrapesByColor = (color: 'czerwony' | 'biały'): GrapeVariety[] => {
  return ALL_GRAPE_VARIETIES.filter((grape) => grape.color === color);
};
